import type { word } from "./types"

export const words: word[] = [
	{ de: "Pferd", en: "horse" },
	{ de: "sowieso", en: "anyway" },
	{ de: "Straße", en: "street" },
	{ de: "Fahrrad", en: "bike" },
	{ de: "Musik", en: "music" },
	{ de: "entlang", en: "along" },
	{ de: "raten", en: "guess" },
	{ de: "Pfanne", en: "pan" },
	{ de: "Herz", en: "heart" },
	{ de: "Heim", en: "home" },
	{ de: "Urlaub", en: "vacation" },
	{ de: "Flugzeug", en: "plane" },
	{ de: "Blume", en: "flower" },
	{ de: "Liebe", en: "love" },
	{ de: "Wiese", en: "meadow" },
	{ de: "Baum", en: "tree" },
	{ de: "Land", en: "country" },
	{ de: "Rand", en: "boundary" },
	{ de: "glücklich", en: "happy" },
	{ de: "Frage", en: "question" },
	{ de: "Antwort", en: "answer" },
	{ de: "Vulkan", en: "vulcano" },
	{ de: "Lösung", en: "solution" },
	{ de: "klein", en: "small" },
	{ de: "unsichtbar", en: "invisible" },
	{ de: "schnell", en: "fast" },
	{ de: "unsicher", en: "insecure" },
	{ de: "selbstbewusst", en: "confident" },
]
